env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=8IVi1whtP6odXUMKnNI423Ellv3OpelkI

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
